/** Matriz de permisos alineada a backend_sasha/db/seed.sql (fuente UI hasta que exista /me). */

export const ROLES = [
  'admin',
  'admin_temporal',
  'secretaria',
  'director',
  'consejeria',
  'coordinador',
  'admisiones',
  'contabilidad',
  'maestro',
  'responsable',
  'alumno',
  'developer',
] as const

export type RoleName = (typeof ROLES)[number]

export type Permission = `${string}:${string}`

const adminPerms: Permission[] = [
  'users:get',
  'users:post',
  'users:put',
  'users:delete',
  'roles:get',
  'roles:put',
  'auditoria:get',
  'configuracion:get',
  'configuracion:put',
  'catalogos:get',
  'catalogos:post',
  'catalogos:put',
  'catalogos:delete',
  'personas:get',
  'personas:post',
  'personas:put',
  'matricula:get',
  'matricula:post',
  'matricula:put',
  'asignacion:get',
  'asignacion:post',
  'asignacion:put',
  'horarios:get',
  'horarios:post',
  'horarios:put',
  'planestudio:get',
  'planestudio:put',
  'asistencia:get',
  'asistencia:post',
  'tareas:get',
  'tareas:post',
  'tareas:put',
  'notas:get',
  'notas:post',
  'notas:put',
  'notas:delete',
  'calificaciones:get',
  'calificaciones:post',
  'calificaciones:put',
  'pagos:get',
  'pagos:post',
  'pagos:put',
  'notificaciones:get',
  'notificaciones:post',
  'notificaciones:put',
  'estadisticas:get',
  'analitica_pagos:get',
  'boveda:post',
  'boveda:get',
  'sace:get',
  'fichas:get',
  'fichas:post',
  'tipos_ficha:post',
  'tipos_ficha:put',
  'expediente:get',
  'coordinaciones:get',
  'coordinaciones:post',
  'coordinaciones:put',
  'excusas:get',
  'excusas:post',
  'tipos_excusa:get',
  'tipos_excusa:post',
]

export const ROLE_PERMISSIONS: Record<RoleName, Permission[]> = {
  admin: adminPerms,
  admin_temporal: [...adminPerms, 'planestudio:post'],
  // Lista propia: hoy coincide con la del director por decisión (DEC-020), pero no se comparte.
  secretaria: [
    'planestudio:get',
    'planestudio:put',
    'asistencia:get',
    'tareas:get',
    'calificaciones:get',
    'personas:get',
    'estadisticas:get',
    'notificaciones:get',
    'sace:get',
    'expediente:get',
    'matricula:get',
    'matricula:post',
    'matricula:put',
    'personas:post',
    'users:post',
    'boveda:post',
    'catalogos:get',
    'fichas:get',
    'fichas:post',
  ],
  // Lista propia: hoy coincide con la de consejería por decisión (DEC-017), pero no se comparte.
  director: [
    'planestudio:get',
    'planestudio:put',
    'asistencia:get',
    'tareas:get',
    'calificaciones:get',
    'personas:get',
    'estadisticas:get',
    'notificaciones:get',
    'sace:get',
    'expediente:get',
    'matricula:get',
    'matricula:post',
    'matricula:put',
    'personas:post',
    'users:post',
    'boveda:post',
    'catalogos:get',
    'fichas:get',
    'fichas:post',
  ],
  consejeria: [
    'planestudio:get',
    'planestudio:put',
    'asistencia:get',
    'tareas:get',
    'calificaciones:get',
    'personas:get',
    'estadisticas:get',
    'notificaciones:get',
    'sace:get',
    'expediente:get',
    'matricula:get',
    'matricula:post',
    'matricula:put',
    'personas:post',
    'users:post',
    'boveda:post',
    'catalogos:get',
    'fichas:get',
    'fichas:post',
    'excusas:get',
    'excusas:post',
  ],
  // Consejería sin matrícula: el backend recorta todo a las clases de sus coordinaciones (DEC-018).
  coordinador: [
    'planestudio:get',
    'planestudio:put',
    'asistencia:get',
    'tareas:get',
    'calificaciones:get',
    'personas:get',
    'estadisticas:get',
    'notificaciones:get',
    'sace:get',
    'expediente:get',
    'fichas:get',
    'fichas:post',
    'excusas:get',
    'excusas:post',
  ],
  // Únicamente matricula (DEC-019): catálogos y personas solo para el asistente.
  admisiones: [
    'matricula:get',
    'matricula:post',
    'matricula:put',
    'personas:get',
    'personas:post',
    'users:post',
    'boveda:post',
    'catalogos:get',
    'notificaciones:get',
  ],
  contabilidad: [
    'pagos:get',
    'pagos:post',
    'pagos:put',
    'cartera:get',
    'analitica_pagos:get',
    'personas:get',
    'notificaciones:get',
    'boveda:post',
    'boveda:get',
  ],
  maestro: [
    'planestudio:get',
    'planestudio:post',
    'planestudio:put',
    'asistencia:get',
    'asistencia:post',
    'tareas:get',
    'tareas:post',
    'tareas:put',
    'calificaciones:get',
    'horarios:get',
    'personas:get',
    'notificaciones:get',
    'notas:get',
    'notas:post',
    'notas:put',
    'notas:delete',
    'mis_estadisticas:get',
    'mi_sace:get',
  ],
  responsable: [
    'tareas:get',
    'calificaciones:get',
    'horarios:get',
    'planestudio:get',
    'pagos:get',
    'pagos:post',
    'notificaciones:get',
    'personas:get',
    'boveda:post',
    'boveda:get',
  ],
  alumno: [
    'tareas:get',
    'calificaciones:get',
    'horarios:get',
    'planestudio:get',
    'notificaciones:get',
  ],
  developer: ['auditoria:get', 'notificaciones:get'],
}

export function roleHasPermission(role: string | null | undefined, permission: Permission): boolean {
  if (!role || !(role in ROLE_PERMISSIONS)) return false
  return ROLE_PERMISSIONS[role as RoleName].includes(permission)
}

/** Unión de permisos: basta con que un rol de la sesión lo tenga. */
export function rolesHavePermission(
  roles: readonly string[] | null | undefined,
  permission: Permission,
): boolean {
  if (!roles?.length) return false
  return roles.some((role) => roleHasPermission(role, permission))
}

export function roleLabel(role: string): string {
  const labels: Record<string, string> = {
    admin: 'Admin',
    admin_temporal: 'Admin temporal',
    secretaria: 'Secretaría',
    director: 'Director',
    consejeria: 'Consejería',
    coordinador: 'Coordinador',
    admisiones: 'Admisiones',
    contabilidad: 'Contabilidad',
    maestro: 'Maestro',
    responsable: 'Responsable',
    alumno: 'Alumno',
    developer: 'Developer',
  }
  return labels[role] ?? role
}
