/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAlumnosRouteImport } from './routes/_app/alumnos'
import { Route as AppAnaliticaPagosRouteImport } from './routes/_app/analitica-pagos'
import { Route as AppAsignacionRouteImport } from './routes/_app/asignacion'
import { Route as AppAsistenciaRouteImport } from './routes/_app/asistencia'
import { Route as AppAuditoriaRouteImport } from './routes/_app/auditoria'
import { Route as AppCalificacionesRouteImport } from './routes/_app/calificaciones'
import { Route as AppConfiguracionRouteImport } from './routes/_app/configuracion'
import { Route as AppControladoresRouteImport } from './routes/_app/controladores'
import { Route as AppCoordinacionesRouteImport } from './routes/_app/coordinaciones'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppEstadisticasRouteImport } from './routes/_app/estadisticas'
import { Route as AppHorariosRouteImport } from './routes/_app/horarios'
import { Route as AppLiberacionNotasRouteImport } from './routes/_app/liberacion-notas'
import { Route as AppMatriculaRouteImport } from './routes/_app/matricula'
import { Route as AppMiPerfilRouteImport } from './routes/_app/mi-perfil'
import { Route as AppNotificacionesAdminRouteImport } from './routes/_app/notificaciones-admin'
import { Route as AppPadresRouteImport } from './routes/_app/padres'
import { Route as AppPagosRouteImport } from './routes/_app/pagos'
import { Route as AppPersonasRouteImport } from './routes/_app/personas'
import { Route as AppPlanEstudioRouteImport } from './routes/_app/plan-estudio'
import { Route as AppRecibosRouteImport } from './routes/_app/recibos'
import { Route as AppSaceRouteImport } from './routes/_app/sace'
import { Route as AppTareasRouteImport } from './routes/_app/tareas'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as AppAlumnoIndexRouteImport } from './routes/_app/alumno/index'
import { Route as AppAlumnoResultadosRouteImport } from './routes/_app/alumno/resultados'
import { Route as AppCatalogosCursosRouteImport } from './routes/_app/catalogos/cursos'
import { Route as AppCatalogosGradosRouteImport } from './routes/_app/catalogos/grados'
import { Route as AppCatalogosModalidadesRouteImport } from './routes/_app/catalogos/modalidades'
import { Route as AppCatalogosPeriodosRouteImport } from './routes/_app/catalogos/periodos'
import { Route as AppCatalogosSeccionesRouteImport } from './routes/_app/catalogos/secciones'
import { Route as AppConsejeriaAlumnosRouteImport } from './routes/_app/consejeria/alumnos'
import { Route as AppConsejeriaHorariosRouteImport } from './routes/_app/consejeria/horarios'
import { Route as AppConsejeriaMaestrosRouteImport } from './routes/_app/consejeria/maestros'
import { Route as AppDisciplinaIndexRouteImport } from './routes/_app/disciplina/index'
import { Route as AppDisciplinaTiposRouteImport } from './routes/_app/disciplina/tipos'
import { Route as AppHijoHorarioRouteImport } from './routes/_app/hijo/horario'
import { Route as AppHijoPagosRouteImport } from './routes/_app/hijo/pagos'
import { Route as AppHijoTareasRouteImport } from './routes/_app/hijo/tareas'
import { Route as AppMaestroIndexRouteImport } from './routes/_app/maestro/index'
import { Route as AppMaestroAnaliticasRouteImport } from './routes/_app/maestro/analiticas'
import { Route as AppResponsableIndexRouteImport } from './routes/_app/responsable/index'
import { Route as AppHijoPlanIndexRouteImport } from './routes/_app/hijo/plan/index'
import { Route as AppHijoPlanAsignacionIdRouteImport } from './routes/_app/hijo/plan/$asignacionId'
import { Route as AppMaestroClasesAsignacionIdRouteImport } from './routes/_app/maestro/clases.$asignacionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAlumnosRoute = AppAlumnosRouteImport.update({
  id: '/alumnos',
  path: '/alumnos',
  getParentRoute: () => AppRoute,
} as any)
const AppAnaliticaPagosRoute = AppAnaliticaPagosRouteImport.update({
  id: '/analitica-pagos',
  path: '/analitica-pagos',
  getParentRoute: () => AppRoute,
} as any)
const AppAsignacionRoute = AppAsignacionRouteImport.update({
  id: '/asignacion',
  path: '/asignacion',
  getParentRoute: () => AppRoute,
} as any)
const AppAsistenciaRoute = AppAsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppCalificacionesRoute = AppCalificacionesRouteImport.update({
  id: '/calificaciones',
  path: '/calificaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppControladoresRoute = AppControladoresRouteImport.update({
  id: '/controladores',
  path: '/controladores',
  getParentRoute: () => AppRoute,
} as any)
const AppCoordinacionesRoute = AppCoordinacionesRouteImport.update({
  id: '/coordinaciones',
  path: '/coordinaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEstadisticasRoute = AppEstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => AppRoute,
} as any)
const AppHorariosRoute = AppHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => AppRoute,
} as any)
const AppLiberacionNotasRoute = AppLiberacionNotasRouteImport.update({
  id: '/liberacion-notas',
  path: '/liberacion-notas',
  getParentRoute: () => AppRoute,
} as any)
const AppMatriculaRoute = AppMatriculaRouteImport.update({
  id: '/matricula',
  path: '/matricula',
  getParentRoute: () => AppRoute,
} as any)
const AppMiPerfilRoute = AppMiPerfilRouteImport.update({
  id: '/mi-perfil',
  path: '/mi-perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacionesAdminRoute = AppNotificacionesAdminRouteImport.update({
  id: '/notificaciones-admin',
  path: '/notificaciones-admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPadresRoute = AppPadresRouteImport.update({
  id: '/padres',
  path: '/padres',
  getParentRoute: () => AppRoute,
} as any)
const AppPagosRoute = AppPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonasRoute = AppPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanEstudioRoute = AppPlanEstudioRouteImport.update({
  id: '/plan-estudio',
  path: '/plan-estudio',
  getParentRoute: () => AppRoute,
} as any)
const AppRecibosRoute = AppRecibosRouteImport.update({
  id: '/recibos',
  path: '/recibos',
  getParentRoute: () => AppRoute,
} as any)
const AppSaceRoute = AppSaceRouteImport.update({
  id: '/sace',
  path: '/sace',
  getParentRoute: () => AppRoute,
} as any)
const AppTareasRoute = AppTareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumnoIndexRoute = AppAlumnoIndexRouteImport.update({
  id: '/alumno/',
  path: '/alumno/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumnoResultadosRoute = AppAlumnoResultadosRouteImport.update({
  id: '/alumno/resultados',
  path: '/alumno/resultados',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogosCursosRoute = AppCatalogosCursosRouteImport.update({
  id: '/catalogos/cursos',
  path: '/catalogos/cursos',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogosGradosRoute = AppCatalogosGradosRouteImport.update({
  id: '/catalogos/grados',
  path: '/catalogos/grados',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogosModalidadesRoute = AppCatalogosModalidadesRouteImport.update({
  id: '/catalogos/modalidades',
  path: '/catalogos/modalidades',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogosPeriodosRoute = AppCatalogosPeriodosRouteImport.update({
  id: '/catalogos/periodos',
  path: '/catalogos/periodos',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogosSeccionesRoute = AppCatalogosSeccionesRouteImport.update({
  id: '/catalogos/secciones',
  path: '/catalogos/secciones',
  getParentRoute: () => AppRoute,
} as any)
const AppConsejeriaAlumnosRoute = AppConsejeriaAlumnosRouteImport.update({
  id: '/consejeria/alumnos',
  path: '/consejeria/alumnos',
  getParentRoute: () => AppRoute,
} as any)
const AppConsejeriaHorariosRoute = AppConsejeriaHorariosRouteImport.update({
  id: '/consejeria/horarios',
  path: '/consejeria/horarios',
  getParentRoute: () => AppRoute,
} as any)
const AppConsejeriaMaestrosRoute = AppConsejeriaMaestrosRouteImport.update({
  id: '/consejeria/maestros',
  path: '/consejeria/maestros',
  getParentRoute: () => AppRoute,
} as any)
const AppDisciplinaIndexRoute = AppDisciplinaIndexRouteImport.update({
  id: '/disciplina/',
  path: '/disciplina/',
  getParentRoute: () => AppRoute,
} as any)
const AppDisciplinaTiposRoute = AppDisciplinaTiposRouteImport.update({
  id: '/disciplina/tipos',
  path: '/disciplina/tipos',
  getParentRoute: () => AppRoute,
} as any)
const AppHijoHorarioRoute = AppHijoHorarioRouteImport.update({
  id: '/hijo/horario',
  path: '/hijo/horario',
  getParentRoute: () => AppRoute,
} as any)
const AppHijoPagosRoute = AppHijoPagosRouteImport.update({
  id: '/hijo/pagos',
  path: '/hijo/pagos',
  getParentRoute: () => AppRoute,
} as any)
const AppHijoTareasRoute = AppHijoTareasRouteImport.update({
  id: '/hijo/tareas',
  path: '/hijo/tareas',
  getParentRoute: () => AppRoute,
} as any)
const AppMaestroIndexRoute = AppMaestroIndexRouteImport.update({
  id: '/maestro/',
  path: '/maestro/',
  getParentRoute: () => AppRoute,
} as any)
const AppMaestroAnaliticasRoute = AppMaestroAnaliticasRouteImport.update({
  id: '/maestro/analiticas',
  path: '/maestro/analiticas',
  getParentRoute: () => AppRoute,
} as any)
const AppResponsableIndexRoute = AppResponsableIndexRouteImport.update({
  id: '/responsable/',
  path: '/responsable/',
  getParentRoute: () => AppRoute,
} as any)
const AppHijoPlanIndexRoute = AppHijoPlanIndexRouteImport.update({
  id: '/hijo/plan/',
  path: '/hijo/plan/',
  getParentRoute: () => AppRoute,
} as any)
const AppHijoPlanAsignacionIdRoute = AppHijoPlanAsignacionIdRouteImport.update({
  id: '/hijo/plan/$asignacionId',
  path: '/hijo/plan/$asignacionId',
  getParentRoute: () => AppRoute,
} as any)
const AppMaestroClasesAsignacionIdRoute =
  AppMaestroClasesAsignacionIdRouteImport.update({
    id: '/maestro/clases/$asignacionId',
    path: '/maestro/clases/$asignacionId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alumnos': typeof AppAlumnosRoute
  '/analitica-pagos': typeof AppAnaliticaPagosRoute
  '/asignacion': typeof AppAsignacionRoute
  '/asistencia': typeof AppAsistenciaRoute
  '/auditoria': typeof AppAuditoriaRoute
  '/calificaciones': typeof AppCalificacionesRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/controladores': typeof AppControladoresRoute
  '/coordinaciones': typeof AppCoordinacionesRoute
  '/dashboard': typeof AppDashboardRoute
  '/estadisticas': typeof AppEstadisticasRoute
  '/horarios': typeof AppHorariosRoute
  '/liberacion-notas': typeof AppLiberacionNotasRoute
  '/matricula': typeof AppMatriculaRoute
  '/mi-perfil': typeof AppMiPerfilRoute
  '/notificaciones-admin': typeof AppNotificacionesAdminRoute
  '/padres': typeof AppPadresRoute
  '/pagos': typeof AppPagosRoute
  '/personas': typeof AppPersonasRoute
  '/plan-estudio': typeof AppPlanEstudioRoute
  '/recibos': typeof AppRecibosRoute
  '/sace': typeof AppSaceRoute
  '/tareas': typeof AppTareasRoute
  '/usuarios': typeof AppUsuariosRoute
  '/alumno/resultados': typeof AppAlumnoResultadosRoute
  '/catalogos/cursos': typeof AppCatalogosCursosRoute
  '/catalogos/grados': typeof AppCatalogosGradosRoute
  '/catalogos/modalidades': typeof AppCatalogosModalidadesRoute
  '/catalogos/periodos': typeof AppCatalogosPeriodosRoute
  '/catalogos/secciones': typeof AppCatalogosSeccionesRoute
  '/consejeria/alumnos': typeof AppConsejeriaAlumnosRoute
  '/consejeria/horarios': typeof AppConsejeriaHorariosRoute
  '/consejeria/maestros': typeof AppConsejeriaMaestrosRoute
  '/disciplina/tipos': typeof AppDisciplinaTiposRoute
  '/hijo/horario': typeof AppHijoHorarioRoute
  '/hijo/pagos': typeof AppHijoPagosRoute
  '/hijo/tareas': typeof AppHijoTareasRoute
  '/maestro/analiticas': typeof AppMaestroAnaliticasRoute
  '/alumno/': typeof AppAlumnoIndexRoute
  '/disciplina/': typeof AppDisciplinaIndexRoute
  '/maestro/': typeof AppMaestroIndexRoute
  '/responsable/': typeof AppResponsableIndexRoute
  '/hijo/plan/$asignacionId': typeof AppHijoPlanAsignacionIdRoute
  '/maestro/clases/$asignacionId': typeof AppMaestroClasesAsignacionIdRoute
  '/hijo/plan/': typeof AppHijoPlanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alumnos': typeof AppAlumnosRoute
  '/analitica-pagos': typeof AppAnaliticaPagosRoute
  '/asignacion': typeof AppAsignacionRoute
  '/asistencia': typeof AppAsistenciaRoute
  '/auditoria': typeof AppAuditoriaRoute
  '/calificaciones': typeof AppCalificacionesRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/controladores': typeof AppControladoresRoute
  '/coordinaciones': typeof AppCoordinacionesRoute
  '/dashboard': typeof AppDashboardRoute
  '/estadisticas': typeof AppEstadisticasRoute
  '/horarios': typeof AppHorariosRoute
  '/liberacion-notas': typeof AppLiberacionNotasRoute
  '/matricula': typeof AppMatriculaRoute
  '/mi-perfil': typeof AppMiPerfilRoute
  '/notificaciones-admin': typeof AppNotificacionesAdminRoute
  '/padres': typeof AppPadresRoute
  '/pagos': typeof AppPagosRoute
  '/personas': typeof AppPersonasRoute
  '/plan-estudio': typeof AppPlanEstudioRoute
  '/recibos': typeof AppRecibosRoute
  '/sace': typeof AppSaceRoute
  '/tareas': typeof AppTareasRoute
  '/usuarios': typeof AppUsuariosRoute
  '/alumno/resultados': typeof AppAlumnoResultadosRoute
  '/catalogos/cursos': typeof AppCatalogosCursosRoute
  '/catalogos/grados': typeof AppCatalogosGradosRoute
  '/catalogos/modalidades': typeof AppCatalogosModalidadesRoute
  '/catalogos/periodos': typeof AppCatalogosPeriodosRoute
  '/catalogos/secciones': typeof AppCatalogosSeccionesRoute
  '/consejeria/alumnos': typeof AppConsejeriaAlumnosRoute
  '/consejeria/horarios': typeof AppConsejeriaHorariosRoute
  '/consejeria/maestros': typeof AppConsejeriaMaestrosRoute
  '/disciplina/tipos': typeof AppDisciplinaTiposRoute
  '/hijo/horario': typeof AppHijoHorarioRoute
  '/hijo/pagos': typeof AppHijoPagosRoute
  '/hijo/tareas': typeof AppHijoTareasRoute
  '/maestro/analiticas': typeof AppMaestroAnaliticasRoute
  '/alumno': typeof AppAlumnoIndexRoute
  '/disciplina': typeof AppDisciplinaIndexRoute
  '/maestro': typeof AppMaestroIndexRoute
  '/responsable': typeof AppResponsableIndexRoute
  '/hijo/plan/$asignacionId': typeof AppHijoPlanAsignacionIdRoute
  '/maestro/clases/$asignacionId': typeof AppMaestroClasesAsignacionIdRoute
  '/hijo/plan': typeof AppHijoPlanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alumnos': typeof AppAlumnosRoute
  '/_app/analitica-pagos': typeof AppAnaliticaPagosRoute
  '/_app/asignacion': typeof AppAsignacionRoute
  '/_app/asistencia': typeof AppAsistenciaRoute
  '/_app/auditoria': typeof AppAuditoriaRoute
  '/_app/calificaciones': typeof AppCalificacionesRoute
  '/_app/configuracion': typeof AppConfiguracionRoute
  '/_app/controladores': typeof AppControladoresRoute
  '/_app/coordinaciones': typeof AppCoordinacionesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/estadisticas': typeof AppEstadisticasRoute
  '/_app/horarios': typeof AppHorariosRoute
  '/_app/liberacion-notas': typeof AppLiberacionNotasRoute
  '/_app/matricula': typeof AppMatriculaRoute
  '/_app/mi-perfil': typeof AppMiPerfilRoute
  '/_app/notificaciones-admin': typeof AppNotificacionesAdminRoute
  '/_app/padres': typeof AppPadresRoute
  '/_app/pagos': typeof AppPagosRoute
  '/_app/personas': typeof AppPersonasRoute
  '/_app/plan-estudio': typeof AppPlanEstudioRoute
  '/_app/recibos': typeof AppRecibosRoute
  '/_app/sace': typeof AppSaceRoute
  '/_app/tareas': typeof AppTareasRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/alumno/resultados': typeof AppAlumnoResultadosRoute
  '/_app/catalogos/cursos': typeof AppCatalogosCursosRoute
  '/_app/catalogos/grados': typeof AppCatalogosGradosRoute
  '/_app/catalogos/modalidades': typeof AppCatalogosModalidadesRoute
  '/_app/catalogos/periodos': typeof AppCatalogosPeriodosRoute
  '/_app/catalogos/secciones': typeof AppCatalogosSeccionesRoute
  '/_app/consejeria/alumnos': typeof AppConsejeriaAlumnosRoute
  '/_app/consejeria/horarios': typeof AppConsejeriaHorariosRoute
  '/_app/consejeria/maestros': typeof AppConsejeriaMaestrosRoute
  '/_app/disciplina/tipos': typeof AppDisciplinaTiposRoute
  '/_app/hijo/horario': typeof AppHijoHorarioRoute
  '/_app/hijo/pagos': typeof AppHijoPagosRoute
  '/_app/hijo/tareas': typeof AppHijoTareasRoute
  '/_app/maestro/analiticas': typeof AppMaestroAnaliticasRoute
  '/_app/alumno/': typeof AppAlumnoIndexRoute
  '/_app/disciplina/': typeof AppDisciplinaIndexRoute
  '/_app/maestro/': typeof AppMaestroIndexRoute
  '/_app/responsable/': typeof AppResponsableIndexRoute
  '/_app/hijo/plan/$asignacionId': typeof AppHijoPlanAsignacionIdRoute
  '/_app/maestro/clases/$asignacionId': typeof AppMaestroClasesAsignacionIdRoute
  '/_app/hijo/plan/': typeof AppHijoPlanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alumnos'
    | '/analitica-pagos'
    | '/asignacion'
    | '/asistencia'
    | '/auditoria'
    | '/calificaciones'
    | '/configuracion'
    | '/controladores'
    | '/coordinaciones'
    | '/dashboard'
    | '/estadisticas'
    | '/horarios'
    | '/liberacion-notas'
    | '/matricula'
    | '/mi-perfil'
    | '/notificaciones-admin'
    | '/padres'
    | '/pagos'
    | '/personas'
    | '/plan-estudio'
    | '/recibos'
    | '/sace'
    | '/tareas'
    | '/usuarios'
    | '/alumno/resultados'
    | '/catalogos/cursos'
    | '/catalogos/grados'
    | '/catalogos/modalidades'
    | '/catalogos/periodos'
    | '/catalogos/secciones'
    | '/consejeria/alumnos'
    | '/consejeria/horarios'
    | '/consejeria/maestros'
    | '/disciplina/tipos'
    | '/hijo/horario'
    | '/hijo/pagos'
    | '/hijo/tareas'
    | '/maestro/analiticas'
    | '/alumno/'
    | '/disciplina/'
    | '/maestro/'
    | '/responsable/'
    | '/hijo/plan/$asignacionId'
    | '/maestro/clases/$asignacionId'
    | '/hijo/plan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alumnos'
    | '/analitica-pagos'
    | '/asignacion'
    | '/asistencia'
    | '/auditoria'
    | '/calificaciones'
    | '/configuracion'
    | '/controladores'
    | '/coordinaciones'
    | '/dashboard'
    | '/estadisticas'
    | '/horarios'
    | '/liberacion-notas'
    | '/matricula'
    | '/mi-perfil'
    | '/notificaciones-admin'
    | '/padres'
    | '/pagos'
    | '/personas'
    | '/plan-estudio'
    | '/recibos'
    | '/sace'
    | '/tareas'
    | '/usuarios'
    | '/alumno/resultados'
    | '/catalogos/cursos'
    | '/catalogos/grados'
    | '/catalogos/modalidades'
    | '/catalogos/periodos'
    | '/catalogos/secciones'
    | '/consejeria/alumnos'
    | '/consejeria/horarios'
    | '/consejeria/maestros'
    | '/disciplina/tipos'
    | '/hijo/horario'
    | '/hijo/pagos'
    | '/hijo/tareas'
    | '/maestro/analiticas'
    | '/alumno'
    | '/disciplina'
    | '/maestro'
    | '/responsable'
    | '/hijo/plan/$asignacionId'
    | '/maestro/clases/$asignacionId'
    | '/hijo/plan'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/alumnos'
    | '/_app/analitica-pagos'
    | '/_app/asignacion'
    | '/_app/asistencia'
    | '/_app/auditoria'
    | '/_app/calificaciones'
    | '/_app/configuracion'
    | '/_app/controladores'
    | '/_app/coordinaciones'
    | '/_app/dashboard'
    | '/_app/estadisticas'
    | '/_app/horarios'
    | '/_app/liberacion-notas'
    | '/_app/matricula'
    | '/_app/mi-perfil'
    | '/_app/notificaciones-admin'
    | '/_app/padres'
    | '/_app/pagos'
    | '/_app/personas'
    | '/_app/plan-estudio'
    | '/_app/recibos'
    | '/_app/sace'
    | '/_app/tareas'
    | '/_app/usuarios'
    | '/_app/alumno/resultados'
    | '/_app/catalogos/cursos'
    | '/_app/catalogos/grados'
    | '/_app/catalogos/modalidades'
    | '/_app/catalogos/periodos'
    | '/_app/catalogos/secciones'
    | '/_app/consejeria/alumnos'
    | '/_app/consejeria/horarios'
    | '/_app/consejeria/maestros'
    | '/_app/disciplina/tipos'
    | '/_app/hijo/horario'
    | '/_app/hijo/pagos'
    | '/_app/hijo/tareas'
    | '/_app/maestro/analiticas'
    | '/_app/alumno/'
    | '/_app/disciplina/'
    | '/_app/maestro/'
    | '/_app/responsable/'
    | '/_app/hijo/plan/$asignacionId'
    | '/_app/maestro/clases/$asignacionId'
    | '/_app/hijo/plan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/alumnos': {
      id: '/_app/alumnos'
      path: '/alumnos'
      fullPath: '/alumnos'
      preLoaderRoute: typeof AppAlumnosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analitica-pagos': {
      id: '/_app/analitica-pagos'
      path: '/analitica-pagos'
      fullPath: '/analitica-pagos'
      preLoaderRoute: typeof AppAnaliticaPagosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/asignacion': {
      id: '/_app/asignacion'
      path: '/asignacion'
      fullPath: '/asignacion'
      preLoaderRoute: typeof AppAsignacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/asistencia': {
      id: '/_app/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof AppAsistenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auditoria': {
      id: '/_app/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calificaciones': {
      id: '/_app/calificaciones'
      path: '/calificaciones'
      fullPath: '/calificaciones'
      preLoaderRoute: typeof AppCalificacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/controladores': {
      id: '/_app/controladores'
      path: '/controladores'
      fullPath: '/controladores'
      preLoaderRoute: typeof AppControladoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coordinaciones': {
      id: '/_app/coordinaciones'
      path: '/coordinaciones'
      fullPath: '/coordinaciones'
      preLoaderRoute: typeof AppCoordinacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estadisticas': {
      id: '/_app/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof AppEstadisticasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/horarios': {
      id: '/_app/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof AppHorariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/liberacion-notas': {
      id: '/_app/liberacion-notas'
      path: '/liberacion-notas'
      fullPath: '/liberacion-notas'
      preLoaderRoute: typeof AppLiberacionNotasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matricula': {
      id: '/_app/matricula'
      path: '/matricula'
      fullPath: '/matricula'
      preLoaderRoute: typeof AppMatriculaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mi-perfil': {
      id: '/_app/mi-perfil'
      path: '/mi-perfil'
      fullPath: '/mi-perfil'
      preLoaderRoute: typeof AppMiPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificaciones-admin': {
      id: '/_app/notificaciones-admin'
      path: '/notificaciones-admin'
      fullPath: '/notificaciones-admin'
      preLoaderRoute: typeof AppNotificacionesAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/padres': {
      id: '/_app/padres'
      path: '/padres'
      fullPath: '/padres'
      preLoaderRoute: typeof AppPadresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pagos': {
      id: '/_app/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof AppPagosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personas': {
      id: '/_app/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AppPersonasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan-estudio': {
      id: '/_app/plan-estudio'
      path: '/plan-estudio'
      fullPath: '/plan-estudio'
      preLoaderRoute: typeof AppPlanEstudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recibos': {
      id: '/_app/recibos'
      path: '/recibos'
      fullPath: '/recibos'
      preLoaderRoute: typeof AppRecibosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sace': {
      id: '/_app/sace'
      path: '/sace'
      fullPath: '/sace'
      preLoaderRoute: typeof AppSaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tareas': {
      id: '/_app/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof AppTareasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alumno/': {
      id: '/_app/alumno/'
      path: '/alumno'
      fullPath: '/alumno/'
      preLoaderRoute: typeof AppAlumnoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alumno/resultados': {
      id: '/_app/alumno/resultados'
      path: '/alumno/resultados'
      fullPath: '/alumno/resultados'
      preLoaderRoute: typeof AppAlumnoResultadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogos/cursos': {
      id: '/_app/catalogos/cursos'
      path: '/catalogos/cursos'
      fullPath: '/catalogos/cursos'
      preLoaderRoute: typeof AppCatalogosCursosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogos/grados': {
      id: '/_app/catalogos/grados'
      path: '/catalogos/grados'
      fullPath: '/catalogos/grados'
      preLoaderRoute: typeof AppCatalogosGradosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogos/modalidades': {
      id: '/_app/catalogos/modalidades'
      path: '/catalogos/modalidades'
      fullPath: '/catalogos/modalidades'
      preLoaderRoute: typeof AppCatalogosModalidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogos/periodos': {
      id: '/_app/catalogos/periodos'
      path: '/catalogos/periodos'
      fullPath: '/catalogos/periodos'
      preLoaderRoute: typeof AppCatalogosPeriodosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogos/secciones': {
      id: '/_app/catalogos/secciones'
      path: '/catalogos/secciones'
      fullPath: '/catalogos/secciones'
      preLoaderRoute: typeof AppCatalogosSeccionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consejeria/alumnos': {
      id: '/_app/consejeria/alumnos'
      path: '/consejeria/alumnos'
      fullPath: '/consejeria/alumnos'
      preLoaderRoute: typeof AppConsejeriaAlumnosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consejeria/horarios': {
      id: '/_app/consejeria/horarios'
      path: '/consejeria/horarios'
      fullPath: '/consejeria/horarios'
      preLoaderRoute: typeof AppConsejeriaHorariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consejeria/maestros': {
      id: '/_app/consejeria/maestros'
      path: '/consejeria/maestros'
      fullPath: '/consejeria/maestros'
      preLoaderRoute: typeof AppConsejeriaMaestrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disciplina/': {
      id: '/_app/disciplina/'
      path: '/disciplina'
      fullPath: '/disciplina/'
      preLoaderRoute: typeof AppDisciplinaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disciplina/tipos': {
      id: '/_app/disciplina/tipos'
      path: '/disciplina/tipos'
      fullPath: '/disciplina/tipos'
      preLoaderRoute: typeof AppDisciplinaTiposRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hijo/horario': {
      id: '/_app/hijo/horario'
      path: '/hijo/horario'
      fullPath: '/hijo/horario'
      preLoaderRoute: typeof AppHijoHorarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hijo/pagos': {
      id: '/_app/hijo/pagos'
      path: '/hijo/pagos'
      fullPath: '/hijo/pagos'
      preLoaderRoute: typeof AppHijoPagosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hijo/tareas': {
      id: '/_app/hijo/tareas'
      path: '/hijo/tareas'
      fullPath: '/hijo/tareas'
      preLoaderRoute: typeof AppHijoTareasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maestro/': {
      id: '/_app/maestro/'
      path: '/maestro'
      fullPath: '/maestro/'
      preLoaderRoute: typeof AppMaestroIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maestro/analiticas': {
      id: '/_app/maestro/analiticas'
      path: '/maestro/analiticas'
      fullPath: '/maestro/analiticas'
      preLoaderRoute: typeof AppMaestroAnaliticasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/responsable/': {
      id: '/_app/responsable/'
      path: '/responsable'
      fullPath: '/responsable/'
      preLoaderRoute: typeof AppResponsableIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hijo/plan/': {
      id: '/_app/hijo/plan/'
      path: '/hijo/plan'
      fullPath: '/hijo/plan/'
      preLoaderRoute: typeof AppHijoPlanIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hijo/plan/$asignacionId': {
      id: '/_app/hijo/plan/$asignacionId'
      path: '/hijo/plan/$asignacionId'
      fullPath: '/hijo/plan/$asignacionId'
      preLoaderRoute: typeof AppHijoPlanAsignacionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maestro/clases/$asignacionId': {
      id: '/_app/maestro/clases/$asignacionId'
      path: '/maestro/clases/$asignacionId'
      fullPath: '/maestro/clases/$asignacionId'
      preLoaderRoute: typeof AppMaestroClasesAsignacionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlumnosRoute: typeof AppAlumnosRoute
  AppAnaliticaPagosRoute: typeof AppAnaliticaPagosRoute
  AppAsignacionRoute: typeof AppAsignacionRoute
  AppAsistenciaRoute: typeof AppAsistenciaRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppCalificacionesRoute: typeof AppCalificacionesRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppControladoresRoute: typeof AppControladoresRoute
  AppCoordinacionesRoute: typeof AppCoordinacionesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEstadisticasRoute: typeof AppEstadisticasRoute
  AppHorariosRoute: typeof AppHorariosRoute
  AppLiberacionNotasRoute: typeof AppLiberacionNotasRoute
  AppMatriculaRoute: typeof AppMatriculaRoute
  AppMiPerfilRoute: typeof AppMiPerfilRoute
  AppNotificacionesAdminRoute: typeof AppNotificacionesAdminRoute
  AppPadresRoute: typeof AppPadresRoute
  AppPagosRoute: typeof AppPagosRoute
  AppPersonasRoute: typeof AppPersonasRoute
  AppPlanEstudioRoute: typeof AppPlanEstudioRoute
  AppRecibosRoute: typeof AppRecibosRoute
  AppSaceRoute: typeof AppSaceRoute
  AppTareasRoute: typeof AppTareasRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppAlumnoResultadosRoute: typeof AppAlumnoResultadosRoute
  AppCatalogosCursosRoute: typeof AppCatalogosCursosRoute
  AppCatalogosGradosRoute: typeof AppCatalogosGradosRoute
  AppCatalogosModalidadesRoute: typeof AppCatalogosModalidadesRoute
  AppCatalogosPeriodosRoute: typeof AppCatalogosPeriodosRoute
  AppCatalogosSeccionesRoute: typeof AppCatalogosSeccionesRoute
  AppConsejeriaAlumnosRoute: typeof AppConsejeriaAlumnosRoute
  AppConsejeriaHorariosRoute: typeof AppConsejeriaHorariosRoute
  AppConsejeriaMaestrosRoute: typeof AppConsejeriaMaestrosRoute
  AppDisciplinaTiposRoute: typeof AppDisciplinaTiposRoute
  AppHijoHorarioRoute: typeof AppHijoHorarioRoute
  AppHijoPagosRoute: typeof AppHijoPagosRoute
  AppHijoTareasRoute: typeof AppHijoTareasRoute
  AppMaestroAnaliticasRoute: typeof AppMaestroAnaliticasRoute
  AppAlumnoIndexRoute: typeof AppAlumnoIndexRoute
  AppDisciplinaIndexRoute: typeof AppDisciplinaIndexRoute
  AppMaestroIndexRoute: typeof AppMaestroIndexRoute
  AppResponsableIndexRoute: typeof AppResponsableIndexRoute
  AppHijoPlanAsignacionIdRoute: typeof AppHijoPlanAsignacionIdRoute
  AppMaestroClasesAsignacionIdRoute: typeof AppMaestroClasesAsignacionIdRoute
  AppHijoPlanIndexRoute: typeof AppHijoPlanIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlumnosRoute: AppAlumnosRoute,
  AppAnaliticaPagosRoute: AppAnaliticaPagosRoute,
  AppAsignacionRoute: AppAsignacionRoute,
  AppAsistenciaRoute: AppAsistenciaRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppCalificacionesRoute: AppCalificacionesRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppControladoresRoute: AppControladoresRoute,
  AppCoordinacionesRoute: AppCoordinacionesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEstadisticasRoute: AppEstadisticasRoute,
  AppHorariosRoute: AppHorariosRoute,
  AppLiberacionNotasRoute: AppLiberacionNotasRoute,
  AppMatriculaRoute: AppMatriculaRoute,
  AppMiPerfilRoute: AppMiPerfilRoute,
  AppNotificacionesAdminRoute: AppNotificacionesAdminRoute,
  AppPadresRoute: AppPadresRoute,
  AppPagosRoute: AppPagosRoute,
  AppPersonasRoute: AppPersonasRoute,
  AppPlanEstudioRoute: AppPlanEstudioRoute,
  AppRecibosRoute: AppRecibosRoute,
  AppSaceRoute: AppSaceRoute,
  AppTareasRoute: AppTareasRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppAlumnoResultadosRoute: AppAlumnoResultadosRoute,
  AppCatalogosCursosRoute: AppCatalogosCursosRoute,
  AppCatalogosGradosRoute: AppCatalogosGradosRoute,
  AppCatalogosModalidadesRoute: AppCatalogosModalidadesRoute,
  AppCatalogosPeriodosRoute: AppCatalogosPeriodosRoute,
  AppCatalogosSeccionesRoute: AppCatalogosSeccionesRoute,
  AppConsejeriaAlumnosRoute: AppConsejeriaAlumnosRoute,
  AppConsejeriaHorariosRoute: AppConsejeriaHorariosRoute,
  AppConsejeriaMaestrosRoute: AppConsejeriaMaestrosRoute,
  AppDisciplinaTiposRoute: AppDisciplinaTiposRoute,
  AppHijoHorarioRoute: AppHijoHorarioRoute,
  AppHijoPagosRoute: AppHijoPagosRoute,
  AppHijoTareasRoute: AppHijoTareasRoute,
  AppMaestroAnaliticasRoute: AppMaestroAnaliticasRoute,
  AppAlumnoIndexRoute: AppAlumnoIndexRoute,
  AppDisciplinaIndexRoute: AppDisciplinaIndexRoute,
  AppMaestroIndexRoute: AppMaestroIndexRoute,
  AppResponsableIndexRoute: AppResponsableIndexRoute,
  AppHijoPlanAsignacionIdRoute: AppHijoPlanAsignacionIdRoute,
  AppMaestroClasesAsignacionIdRoute: AppMaestroClasesAsignacionIdRoute,
  AppHijoPlanIndexRoute: AppHijoPlanIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
